### ISSUE TITLE
Dogecoiners

### ISSUE THREAD

**Issue by Astrum97** [LinumLabs/UnlockTheBlock#102]
Name: Nicolaas Maree
Name of Team: Dogecoiners
Student Number: 24991759
University: NWU
Location: Potchefstroom
Target Sector: Software development
Twitter (optional): N/A
LinkedIn (optional):  https://www.linkedin.com/in/nmaree79/

**Comment by Zander-Labuschagne** [comment]
Name: Zander Labuschagne
Name of Team: Dogecoiners
Student Number: 23585137
University: North-West University
Location: Potchefstroom
Target Sector: Software Development
Twitter (optional): N/A
LinkedIn (optional): https://www.linkedin.com/in/zanderlabuschagne/
