### ISSUE TITLE
Thomas

### ISSUE THREAD

**Issue by Tom2718** [LinumLabs/UnlockTheBlock#104]
Name: Thomas
Name of Team: N/A 
Student Number: TMLTHO001
University: UCT
Location: Cape Town
Target Sector: Software Development

**Comment by Tom2718** [comment]
- [ ] Find Team Members

- [ ] Attend Unlock the Block Hackathon

- [ ] Create Killer DApp

- [ ] HODL to the Moon

**Comment by jarry401** [comment]
Name: Jared
Name of Team: N/A
Student Number: TMLJAR001
University: UCT
Location: Cape Town
Target Sector: Identity

**Comment by Tom2718** [comment]
#108
