### ISSUE TITLE
UnlockTheBlock

### ISSUE THREAD

**Issue by zulucomputer** [LinumLabs/UnlockTheBlock#139]
Name: Mathonsi, Thabang
Name of Team:
Student Number: MTHTHA090
University: University of Cape Town
Location: Cape Town/ Johannesburg
Target Sector: FinTech

**Comment by andytudhope** [comment]
Applications are now closed, sorry.

**Comment by andytudhope** [comment]
Seems like you submitted the rest of the application before the closing date. Opening again for now so we can consider you.

**Comment by zulucomputer** [comment]
Alright, thank you.  Is there anything else I need to do on my end?  I think everything should be in order.
