### ISSUE TITLE
Template issue 

### ISSUE THREAD

**Issue by Titroid** [LinumLabs/UnlockTheBlock#2]
Name: William Chandler De Kock
Name of Team: N/A as of yet
Student Number: 18291929
University: Stellenbosch University
Location: Stellenbosch 
Target Sector: FinTech
LinkedIn: https://www.linkedin.com/in/william-de-kock-a89a2190/

**Comment by cbekker1** [comment]
Hey Chan, 
Good to see you applied. Let me know if you want to start a team
