### ISSUE TITLE
MT - Simplimantis

### ISSUE THREAD

**Issue by Masharty** [LinumLabs/UnlockTheBlock#53]
Name: Masharty Tembo
Name of Team: Simplimantis
Student Number: TMBMAS001 
University: University of Cape Town (Alumni)
Location: Cape Town
Target Sector: Software Development
LinkedIn (optional): https://www.linkedin.com/in/masharty-tembo-a4787a2b/

My Interest in the hackathon: Excited to learn more about blockchain technology and its applications.
How I heard about it: A friend via a cryptocurrency WhatsApp group.

**Comment by mthlongwane** [comment]
Hi! Im a uct computer science student whos interested in knowing more about crypto-currencies. we should have a chat sometime.

www.linkedin.com/in/mzwenhlanhla-hlongwane-6497b661

**Comment by andytudhope** [comment]
Hey Thando! Nisa looks really awesome, that is a very, very neat idea with great possibility. Super excited to have you sign up for this and look forward to meeting you down in the Cape next year 😉
