### ISSUE TITLE
Moyo Business Advisory Issue

### ISSUE THREAD

**Issue by jlacock** [LinumLabs/UnlockTheBlock#76]
Name: Jaco la Cock
Name of team: Moyo Mavericks
Location: Gauteng
Target sector: Fintech

**Comment by MerikeMalan** [comment]
Name: Merike Malan
Name of Team: Moyo Mavericks
Student Number: 12105059
University: University of Pretoria
Location: Gauteng
Target Sector: FinTech
Twitter: @MeriXoxo
LinkedIn (optional): https://www.linkedin.com/in/merike-malan-74072384/

**Comment by Venteret** [comment]
Name: Etienne Venter
Name of team: Moyo Mavericks
Location: Gauteng
Target sector: Fintech
