### ISSUE TITLE
Wild Cats

### ISSUE THREAD

**Issue by 93will93** [LinumLabs/UnlockTheBlock#93]
Name: William Becerra
Name of Team: Wild Cats
Student Number: 789 146
University: Wits University
Location: Johannesburg South Africa
Target Sector: FinTech

**Comment by bulimdj** [comment]
#

**Comment by bulimdj** [comment]
[Readme.txt](https://github.com/LinumLabs/UnlockTheBlock/files/1497224/Readme.txt)
